# Generated by Django 3.2.2 on 2021-05-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('desc', models.CharField(default='', max_length=255)),
                ('staff_only', models.BooleanField(default=False)),
                ('my_json', models.JSONField(blank=True, default={})),
                ('counter', models.IntegerField(default=0)),
            ],
        ),
    ]
