# Generated by Django 3.2.2 on 2021-05-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='counter',
        ),
        migrations.RemoveField(
            model_name='room',
            name='staff_only',
        ),
        migrations.AlterField(
            model_name='room',
            name='my_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
