# Generated by Django 3.2.2 on 2021-05-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_room_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='staff_only',
            field=models.BooleanField(default=False),
        ),
    ]
